#! /bin/sh

bspc monitor -d www term work music misc system

bspc config border_width        2
bspc config window_gap          5
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding 15
bspc config focus_follows_pointer true

bspc rule -a htop desktop=^6
bspc rule -a ranger desktop=^6
bspc rule -a ncmpcpp desktop=^4

sxhkd &
${HOME}/.config/bspwm/panel
