#!/bin/bash
bspc config border_width		2
bspc config window_gap         40

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config initial_polarity second_child
bspc config ignore_ewmh_focus true
bspc config top_padding 20

bspc config focused_border_color \#$white
bspc config active_border_color \#$white
bspc config normal_border_color \#$white
bspc config urgent_border_color \#$white

bspc config focused_locked_border_color \#$white
bspc config active_locked_border_color \#$white
bspc config normal_locked_border_color \#$white

bspc config focused_sticky_border_color \#$white
bspc config active_sticky_border_color \#$white
bspc config normal_sticky_border_color \#$white

bspc config focused_private_border_color \#$white
bspc config active_private_border_color \#$white
bspc config normal_private_border_color \#$white

bspc config -m HDMI-3 top_padding 20

bspc monitor HDMI-3 -d web term work music misc sys
#bspc monitor DVI-1 -d 8
#bspc monitor HDMI-0 -d 9

bspc rule -a htop desktop=^6
bspc rule -a ranger desktop=^6
bspc rule -a ncmpcpp desktop=^4

# Workdsace 2
bspc config -d 2 window_gap 5
bspc config -d 2 top_padding 85
bspc config -d 2 right_padding 85
bspc config -d 2 bottom_padding 85
bspc config -d 2 left_padding 85


# bspc config -d $ws1 window_gap 40

# Workspace *
bspc rule -a feh floating=on
bspc rule -a dmenu border=on
bspc rule -a thunar floating=on

# Load some stuff
#xsetroot -cursor_name left_ptr
#dunst &
#nitrogen --restore &
#sxhkd &

# Launches mpd
#mpd &

# auto usb mount
#devmon &

# Compton
compton --config ~/.compton &
# compton --backend glx --paint-on-overlay --vsync opengl-swc &

# Multi monitor
# xrandr --output DVI-0 --mode 1920x1080 --rate 60 --left-of DVI-1 --output DVI-1 --mode 1280x1024 --rate 75 &

#xrandr --output DVI-0 --mode 1920x1080 --rate 60 --primary --left-of DVI-1 --output DVI-1 --mode 1280x1024 --rate 75 --output HDMI-0 --mode 1920x1080 --rate 60 --right-of DVI-1 &
#xrandr --output DVI-0 --mode 1920x1080 --rate 60 --primary --left-of DVI-1 --output DVI-1 --mode 1280x1024 --rate 75 --output HDMI-0 --mode 1920x1080 --rate 60 --below DVI-0 &
#sleep 3s &&

# Papes
# ~/dotfiles/scripts/wallpaper.sh &
#feh --bg-fill ~/Pictures/papes2/killlakill4.png &

# lemonbar
#sleep .5s &&
#~/.config/lemonbar/clock.sh &
#sleep 1s &&
#~/.config/lemonbar/workspace.sh &
#sleep .5s &&
#~/.config/lemonbar/music.sh &
#~/dotfiles/afterx.sh &
~/.config/bspwm/panel &
