#! /bin/sh

bspc monitor -d 1 2 3 4 5

bspc config border_width		2
bspc config window_gap			5
bspc config top_padding			12
bspc config bottom_padding		0
bspc config bottom_padding		-5
bspc config left_padding		-5
bspc config right_padding		-5
bspc config split_ratio			0.50
bspc config focus_follows_pointer	true
bspc config auto_alternate		true
bspc config auto_cancel			true
bspc config history_aware_focus		true

bspc rule -a google-chrome desktop=^3
bspc rule -a Skype floating=on desktop=^10
bspc rule -a Pidgin floating=on desktop=^10

rm -f $PANEL_FIFO
mkfifo $PANEL_FIFO
sxhkd &
~/.config/bspwm/panel/panel &
